# Generated by Django 4.1 on 2022-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория Контактов', 'verbose_name_plural': 'Категории контактов'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Категория контактов'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='contacts_photo/%Y/%m/', verbose_name='Фото'),
        ),
    ]
