# Generated by Django 4.1 on 2022-08-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.category', verbose_name='Категория контактов'),
        ),
    ]
